CREATE TABLE notifications (
                                      uuid uuid NOT NULL,
                                      txt varchar NOT NULL,
                                      "destination" int2 NOT NULL,
                                      server_timestamp timestamp NOT NULL,
                                      last_updated timestamp NOT NULL,
                                      CONSTRAINT notifications_pk PRIMARY KEY (uuid)
);

-- Column comments

COMMENT ON COLUMN notifications.uuid IS 'UUID of the notifications, generated at the client';
COMMENT ON COLUMN notifications.txt IS 'Notification Text';
COMMENT ON COLUMN notifications."destination" IS 'Notification destination';
COMMENT ON COLUMN notifications.server_timestamp IS 'Timestamp generated by server';
COMMENT ON COLUMN notifications.last_updated IS 'Last updated timestamp';
